<?php
require_once "config.php"; $category = trim($_GET["category"] ?? "");
if ($category !== "") { $stmt = mysqli_prepare($conn, "SELECT id,title,category,notice_date,description FROM notices WHERE category=? ORDER BY notice_date DESC,id DESC"); mysqli_stmt_bind_param($stmt,"s",$category); mysqli_stmt_execute($stmt); $result=mysqli_stmt_get_result($stmt); }
else { $result=mysqli_query($conn,"SELECT id,title,category,notice_date,description FROM notices ORDER BY notice_date DESC,id DESC"); }
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>View Notices</title><link rel="stylesheet" href="style.css"></head><body>
<nav><div class="brand">📢 Department Notice Archive</div><div><a href="index.php">Home</a><a href="view.php">View Notices</a></div></nav><div class="container"><section class="card"><h2>Notice Archive</h2><form class="filter" method="get" action="view.php"><label for="category">Filter by Category</label><select id="category" name="category"><option value="">All Categories</option><option value="Academic" <?= $category==="Academic"?"selected":"" ?>>Academic</option><option value="Exam" <?= $category==="Exam"?"selected":"" ?>>Exam</option><option value="Event" <?= $category==="Event"?"selected":"" ?>>Event</option><option value="Placement" <?= $category==="Placement"?"selected":"" ?>>Placement</option><option value="General" <?= $category==="General"?"selected":"" ?>>General</option></select><button type="submit">Search</button><a class="reset" href="view.php">Reset</a></form>
<?php if (mysqli_num_rows($result)===0): ?><p class="empty">No notices found.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>ID</th><th>Title</th><th>Category</th><th>Date</th><th>Description</th></tr></thead><tbody><?php while($row=mysqli_fetch_assoc($result)): ?><tr><td><?=htmlspecialchars($row["id"])?></td><td><?=htmlspecialchars($row["title"])?></td><td><?=htmlspecialchars($row["category"])?></td><td><?=htmlspecialchars($row["notice_date"])?></td><td><?=htmlspecialchars($row["description"])?></td></tr><?php endwhile; ?></tbody></table></div><?php endif; ?></section></div>
</body></html><?php if(isset($stmt))mysqli_stmt_close($stmt); mysqli_close($conn); ?>
